/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlocRouteImport } from './routes/bloc'
import { Route as IndexRouteImport } from './routes/index'

const BlocRoute = BlocRouteImport.update({
  id: '/bloc',
  path: '/bloc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloc': typeof BlocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloc': typeof BlocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloc': typeof BlocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bloc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bloc'
  id: '__root__' | '/' | '/bloc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocRoute: typeof BlocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bloc': {
      id: '/bloc'
      path: '/bloc'
      fullPath: '/bloc'
      preLoaderRoute: typeof BlocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocRoute: BlocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
